// TS mirror of the engine's team-name canonicalisation (adapters/teams.py),
// scoped to what the UCL live endpoint needs: football-data.org spellings of
// the 36 league-phase clubs. Unknown names pass through unchanged so a card
// still renders (with the grey fallback identity from lib/ucl/clubs).

const ALIASES: Record<string, string> = {
  'aek athens': 'AEK Athens',
  'pae aek': 'AEK Athens',
  arsenal: 'Arsenal',
  'arsenal fc': 'Arsenal',
  'aston villa': 'Aston Villa',
  'aston villa fc': 'Aston Villa',
  atleti: 'Atlético Madrid',
  'atletico madrid': 'Atlético Madrid',
  'atlético madrid': 'Atlético Madrid',
  'club atletico de madrid': 'Atlético Madrid',
  'club atlético de madrid': 'Atlético Madrid',
  barcelona: 'Barcelona',
  'fc barcelona': 'Barcelona',
  barça: 'Barcelona',
  barca: 'Barcelona',
  bayern: 'Bayern Munich',
  'bayern munich': 'Bayern Munich',
  'bayern münchen': 'Bayern Munich',
  'fc bayern münchen': 'Bayern Munich',
  'fc bayern munchen': 'Bayern Munich',
  'bodo/glimt': 'Bodø/Glimt',
  'bodø/glimt': 'Bodø/Glimt',
  'fk bodo/glimt': 'Bodø/Glimt',
  'fk bodø/glimt': 'Bodø/Glimt',
  dortmund: 'Borussia Dortmund',
  'b dortmund': 'Borussia Dortmund',
  'borussia dortmund': 'Borussia Dortmund',
  'bv borussia 09 dortmund': 'Borussia Dortmund',
  'club brugge': 'Club Brugge',
  'club brugge kv': 'Club Brugge',
  como: 'Como',
  'como 1907': 'Como',
  fenerbahce: 'Fenerbahçe',
  fenerbahçe: 'Fenerbahçe',
  'fenerbahce sk': 'Fenerbahçe',
  'fenerbahçe sk': 'Fenerbahçe',
  feyenoord: 'Feyenoord',
  'feyenoord rotterdam': 'Feyenoord',
  galatasaray: 'Galatasaray',
  'galatasaray sk': 'Galatasaray',
  inter: 'Inter Milan',
  'inter milan': 'Inter Milan',
  'fc internazionale milano': 'Inter Milan',
  lask: 'LASK',
  'lask linz': 'LASK',
  lens: 'Lens',
  'rc lens': 'Lens',
  lille: 'Lille',
  'losc lille': 'Lille',
  'lille osc': 'Lille',
  liverpool: 'Liverpool',
  'liverpool fc': 'Liverpool',
  'man city': 'Manchester City',
  'manchester city': 'Manchester City',
  'manchester city fc': 'Manchester City',
  'man united': 'Manchester United',
  'man utd': 'Manchester United',
  'manchester united': 'Manchester United',
  'manchester united fc': 'Manchester United',
  napoli: 'Napoli',
  'ssc napoli': 'Napoli',
  psv: 'PSV Eindhoven',
  'psv eindhoven': 'PSV Eindhoven',
  paris: 'Paris Saint-Germain',
  psg: 'Paris Saint-Germain',
  'paris saint-germain': 'Paris Saint-Germain',
  'paris saint-germain fc': 'Paris Saint-Germain',
  porto: 'Porto',
  'fc porto': 'Porto',
  'rb leipzig': 'RB Leipzig',
  leipzig: 'RB Leipzig',
  'real betis': 'Real Betis',
  'real betis balompié': 'Real Betis',
  'real betis balompie': 'Real Betis',
  'real madrid': 'Real Madrid',
  'real madrid cf': 'Real Madrid',
  roma: 'Roma',
  'as roma': 'Roma',
  sabah: 'Sabah FK',
  'sabah fk': 'Sabah FK',
  shakhtar: 'Shakhtar Donetsk',
  shaktar: 'Shakhtar Donetsk',
  'shakhtar donetsk': 'Shakhtar Donetsk',
  'fc shakhtar donetsk': 'Shakhtar Donetsk',
  'slavia praha': 'Slavia Prague',
  'slavia prague': 'Slavia Prague',
  'sk slavia praha': 'Slavia Prague',
  'slovan bratislava': 'Slovan Bratislava',
  'sl. bratislava': 'Slovan Bratislava',
  's bratislava': 'Slovan Bratislava',
  'šk slovan bratislava': 'Slovan Bratislava',
  sporting: 'Sporting CP',
  'sporting cp': 'Sporting CP',
  'sporting clube de portugal': 'Sporting CP',
  stuttgart: 'VfB Stuttgart',
  'vfb stuttgart': 'VfB Stuttgart',
  viking: 'Viking',
  'viking fk': 'Viking',
  villarreal: 'Villarreal',
  'villarreal cf': 'Villarreal',
};

export function canonicalTeam(name: string): string {
  return ALIASES[name.trim().toLowerCase()] ?? name.trim();
}
