import { describe, expect, it } from 'vitest';
import {
  actionsForPosition,
  defconProfile,
  rankDefcon,
  type DefconMatch,
  type DefconPosition,
  type DefconProfile,
} from '@/lib/defcon/profile';
import fixtures from './fixtures/defcon_cases.json';

// Part 1 mirrors engine/tests/test_engine.py DEFCON cases exactly (TASKS.md 1.1).
// Part 2 replays tests/fixtures/defcon_cases.json, generated by the Python
// engine (scripts/generate_defcon_fixtures.py) — the parity contract between
// defcon.py and profile.ts. Regenerate the fixture after changing either side.

describe('defconProfile — engine test mirror', () => {
  it('defender: threshold 10, blended hit rate and near misses', () => {
    const hist: DefconMatch[] = [10, 12, 9, 8, 11, 9].map((a) => ({ minutes: 90, cbit: a }));
    const p = defconProfile('1', 'Def', 'T', 'DEF', 5.0, hist);
    expect(p).not.toBeNull();
    expect(p!.matches_considered).toBe(6);
    // last5 = [12,9,8,11,9] -> 2/5 hits; season 3/6
    expect(p!.hit_rate).toBeCloseTo(0.6 * (2 / 5) + 0.4 * (3 / 6), 9);
    expect(p!.near_miss_rate).toBeCloseTo(3 / 6, 9); // 9,8,9 within 2 below 10
    expect(p!.defcon_xpts).toBeCloseTo(p!.hit_rate * 2, 9);
  });

  it('midfielder: recoveries count toward threshold 12', () => {
    const hist: DefconMatch[] = [
      { minutes: 90, cbit: 7, recoveries: 5 },
      { minutes: 90, cbit: 6, recoveries: 4 },
    ];
    const p = defconProfile('2', 'Mid', 'T', 'MID', 6.0, hist);
    expect(p!.hit_rate).toBeCloseTo(0.5, 9);
  });

  it('ignores short cameos; goalkeepers have no profile', () => {
    const hist: DefconMatch[] = [
      { minutes: 20, cbit: 11 },
      { minutes: 90, cbit: 11 },
    ];
    const p = defconProfile('3', 'Def', 'T', 'DEF', 5.0, hist);
    expect(p!.matches_considered).toBe(1);
    expect(defconProfile('4', 'GK', 'T', 'GK', 5.0, hist)).toBeNull();
  });
});

describe('defconProfile — parity with the Python engine fixture', () => {
  const NUMERIC_FIELDS = [
    'hit_rate',
    'mean_actions',
    'near_miss_rate',
    'consistency',
    'defcon_xpts',
    'value_per_million',
  ] as const;

  for (const c of fixtures.cases) {
    it(c.label, () => {
      const { player_id, name, team, position, price, history, options } = c.input;
      const p = defconProfile(player_id, name, team, position as DefconPosition, price, history, {
        minMinutes: (options as Record<string, number>).min_minutes,
        nearMissMargin: (options as Record<string, number>).near_miss_margin,
        recencyWeight: (options as Record<string, number>).recency_weight,
      });
      if (c.expected === null) {
        expect(p).toBeNull();
        return;
      }
      expect(p).not.toBeNull();
      const expected = c.expected as unknown as DefconProfile;
      expect(p!.matches_considered).toBe(expected.matches_considered);
      expect(p!.last5_actions).toEqual(expected.last5_actions);
      for (const field of NUMERIC_FIELDS) {
        expect(p![field], field).toBeCloseTo(expected[field], 9);
      }
    });
  }
});

describe('helpers', () => {
  it('actionsForPosition excludes recoveries for defenders only', () => {
    const m: DefconMatch = { minutes: 90, cbit: 6, recoveries: 4 };
    expect(actionsForPosition(m, 'DEF')).toBe(6);
    expect(actionsForPosition(m, 'MID')).toBe(10);
    expect(actionsForPosition(m, 'FWD')).toBe(10);
  });

  it('rankDefcon sorts descending without mutating input', () => {
    const mk = (id: string, xpts: number, value: number): DefconProfile => ({
      player_id: id,
      name: id,
      team: 'T',
      position: 'DEF',
      price: 5,
      matches_considered: 1,
      hit_rate: xpts / 2,
      mean_actions: 10,
      near_miss_rate: 0,
      consistency: 1,
      defcon_xpts: xpts,
      value_per_million: value,
      last5_actions: [10],
    });
    const profiles = [mk('a', 0.8, 0.16), mk('b', 1.6, 0.32), mk('c', 1.2, 0.24)];
    expect(rankDefcon(profiles).map((p) => p.player_id)).toEqual(['b', 'c', 'a']);
    expect(rankDefcon(profiles, 'value_per_million').map((p) => p.player_id)).toEqual([
      'b',
      'c',
      'a',
    ]);
    expect(profiles.map((p) => p.player_id)).toEqual(['a', 'b', 'c']); // untouched
  });
});
