// FPL Defensive Contribution (DEFCON) analytics — TypeScript port of
// engine/ucl_engine/defcon.py (TASKS.md 1.1). Semantics must match the Python
// implementation exactly; parity is enforced by tests/fixtures/defcon_cases.json,
// which is generated BY the Python engine (scripts/generate_defcon_fixtures.py).
// If you change anything here, change defcon.py the same way and regenerate.
//
// RULE (2025/26 onward; verify at the start of each FPL season)
//   Defenders:            +2 pts when clearances+blocks+interceptions+tackles (CBIT) >= 10 in a match
//   Midfielders/Forwards: +2 pts when CBIT + ball recoveries >= 12 in a match
//   Awarded at most once per match.
//
// Profile fields stay snake_case to match the engine's JSON output; one shape
// on both sides of the pipeline means no field-mapping bugs.

export type DefconPosition = 'DEF' | 'MID' | 'FWD' | 'GK';

export const THRESHOLD: Record<DefconPosition, number | null> = {
  DEF: 10,
  MID: 12,
  FWD: 12,
  GK: null,
};

export const DEFCON_POINTS = 2;

export interface DefconMatch {
  minutes: number;
  cbit: number; // clearances + blocks + interceptions + tackles
  recoveries?: number;
  opponent?: string | null;
  was_home?: boolean | null;
}

/** Defenders count CBIT only; MID/FWD add recoveries. */
export function actionsForPosition(m: DefconMatch, position: DefconPosition): number {
  return position === 'DEF' ? m.cbit : m.cbit + (m.recoveries ?? 0);
}

export interface DefconProfile {
  player_id: string;
  name: string;
  team: string;
  position: DefconPosition;
  price: number;
  matches_considered: number;
  hit_rate: number;
  mean_actions: number;
  near_miss_rate: number;
  consistency: number;
  defcon_xpts: number;
  value_per_million: number;
  last5_actions: number[];
}

export interface DefconProfileOptions {
  minMinutes?: number;
  nearMissMargin?: number;
  recencyWeight?: number;
}

function mean(xs: number[]): number {
  return xs.reduce((s, x) => s + x, 0) / xs.length;
}

/** Population standard deviation, matching Python's statistics.pstdev. */
function pstdev(xs: number[]): number {
  const mu = mean(xs);
  return Math.sqrt(xs.reduce((s, x) => s + (x - mu) * (x - mu), 0) / xs.length);
}

/**
 * Build a DEFCON profile from match history. Only matches with >= minMinutes
 * count (a 15-minute cameo tells you nothing about a player's engine).
 * `recencyWeight` blends last-5-match hit rate with season hit rate so the
 * number reacts to role changes without being whipsawed by one game.
 */
export function defconProfile(
  playerId: string,
  name: string,
  team: string,
  position: DefconPosition,
  price: number,
  history: DefconMatch[],
  { minMinutes = 60, nearMissMargin = 2, recencyWeight = 0.6 }: DefconProfileOptions = {}
): DefconProfile | null {
  const thr = THRESHOLD[position];
  if (thr === null || thr === undefined) return null;

  const games = history.filter((m) => m.minutes >= minMinutes);
  if (games.length === 0) return null;

  const acts = games.map((m) => actionsForPosition(m, position));
  const hits = acts.map((a) => (a >= thr ? 1 : 0));
  const near = acts.map((a) => (thr - nearMissMargin <= a && a < thr ? 1 : 0));

  const seasonHit = mean(hits);
  const last5 = acts.slice(-5);
  const last5Hit = mean(last5.map((a) => (a >= thr ? 1 : 0)));
  const blendedHit =
    games.length >= 5 ? recencyWeight * last5Hit + (1 - recencyWeight) * seasonHit : seasonHit;

  const mu = mean(acts);
  const sd = acts.length > 1 ? pstdev(acts) : 0;
  const consistency = Math.max(0, 1 - (mu !== 0 ? sd / mu : 1));
  const xpts = blendedHit * DEFCON_POINTS;

  return {
    player_id: playerId,
    name,
    team,
    position,
    price,
    matches_considered: games.length,
    hit_rate: blendedHit,
    mean_actions: mu,
    near_miss_rate: mean(near),
    consistency,
    defcon_xpts: xpts,
    value_per_million: price !== 0 ? xpts / price : 0,
    last5_actions: last5,
  };
}

/** Sort profiles descending by a numeric field (default: DEFCON xPts). */
export function rankDefcon(
  profiles: DefconProfile[],
  by:
    | 'hit_rate'
    | 'mean_actions'
    | 'near_miss_rate'
    | 'consistency'
    | 'defcon_xpts'
    | 'value_per_million' = 'defcon_xpts'
): DefconProfile[] {
  return [...profiles].sort((a, b) => b[by] - a[by]);
}
